### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by ghost** [jainamoswal/BotStatus#1]
can you make tutorial or guide build using VPS

**Comment by jainamoswal** [comment]
Hey!
It's build to run on GitHub actions.

If you still want to run this on VPS, you can fork the bot.py and put environment variables and somehow run the script at schedule, or at any event.

And I'm going to put a tutorial on GitHub actions deploy søøn. Maybe it finds you in easy.

**Comment by jainamoswal** [comment]
Now, this is been converted to GitHub actions, 💁🏻 so it will only be usable for GitHub actions.

In near future, I'll think for a branch for using this script deployable on VPS.
