### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by devilxsam** [jainamoswal/BotStatus#6]
Run jainamoswal/botstatus@main
  env:
    GITHUB_TOKEN: ***
    BOTS: ***
    SESSION: ***
    APP_ID: ***
    API_HASH: ***
    IDS: ***
Run pip install --upgrade pytz telethon pygithub pip > ignoreme.txt [2](https://github.com/devilxsam/BotStatus1/actions/runs/7627165653/job/20775200635#step:2:2)>&1
  pip install --upgrade pytz telethon pygithub pip > ignoreme.txt 2>&1
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GITHUB_TOKEN: ***
    BOTS: ***
    SESSION: ***
    APP_ID: ***
    API_HASH: ***
    IDS: ***
Run python /home/runner/work/_actions/jainamoswal/botstatus/main/main.py
  python /home/runner/work/_actions/jainamoswal/botstatus/main/main.py
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GITHUB_TOKEN: ***
    BOTS: ***
    SESSION: ***
    APP_ID: ***
    API_HASH: ***
    IDS: ***
/usr/lib/python[3](https://github.com/devilxsam/BotStatus1/actions/runs/7627165653/job/20775200635#step:2:3)/dist-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'spaceb.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
:::::::::::::::::::::: ⏲️ Action started successfully ⏲️ ::::::::::::::::::::::

◻️ Telethon version : 1.33.1
◻️ Platform : Linux
◻️ Platform release : 6.2.0-1018-azure
◻️ OS version : #18~22.0[4](https://github.com/devilxsam/BotStatus1/actions/runs/7627165653/job/20775200635#step:2:4).1-Ubuntu

🔸 𝐓𝐌 𝐅𝐢𝐥𝐞 𝐒𝐭𝐫𝐞𝐚𝐦 𝐁𝐨𝐭 [@TM_FileStreamBot] is 🔴
🔸 𝙏𝙈 - 𝙎𝙖𝙫𝙚 𝙍𝙚𝙨𝙩𝙧𝙞𝙘𝙩𝙚𝙙 𝘽𝙤𝙩 [@TM_SaveRestrictedBot] is 🟢
Traceback (most recent call last):
  File "/home/runner/work/_actions/jainamoswal/botstatus/main/main.py", line 127, in <module>
    contents = repo.get_contents(file_name) 
  File "/home/runner/.local/lib/python3.10/site-packages/github/Repository.py", line 21[5](https://github.com/devilxsam/BotStatus1/actions/runs/7627165653/job/20775200635#step:2:5)1, in get_contents
    headers, data = self._requester.requestJsonAndCheck(
  File "/home/runner/.local/lib/python3.10/site-packages/github/Requester.py", line 4[9](https://github.com/devilxsam/BotStatus1/actions/runs/7627165653/job/20775200635#step:2:10)4, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/home/runner/.local/lib/python3.[10](https://github.com/devilxsam/BotStatus1/actions/runs/7627165653/job/20775200635#step:2:11)/site-packages/github/Requester.py", line 5[25](https://github.com/devilxsam/BotStatus1/actions/runs/7627165653/job/20775200635#step:2:27), in __check
    raise self.createException(status, responseHeaders, data)
github.GithubException.UnknownObjectException: [40](https://github.com/devilxsam/BotStatus1/actions/runs/7627165653/job/20775200635#step:2:43)4 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/repos/contents#get-repository-content"}
Error: Process completed with exit code 1.

**Comment by jainamoswal** [comment]
Due to recent updates in GitHub, default API doesn't have access to edit/view your repositories. 
To solve this, you will have to create a [Personal Access Token](https://github.com/settings/tokens) and then add it to the secrets of your repo. 

let me know if it works.
